name: Pack and Publish

on:
  push:
    tags:
      - 'v*'
    branch:
      - 'master'
      - 'main'
    
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  build_pack:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: Pack library
      run: dotnet pack ILTemplates/ILTemplates.csproj -c Release -o ./Packed

    - name: Test
      run: |
        dotnet new -i ./Packed/*nupkg
        cd tests
        ./run_test.ps1
        cd ..
      shell: pwsh

    - name: Upload nuget
      uses: actions/upload-artifact@v2.2.1
      with: 
        name: Templates
        path: ./Packed
    - name: Publish to github package registry
      run: dotnet nuget push -s 'https://nuget.pkg.github.com/Ilia-Kosenkov/index.json' -k $GITHUB_TOKEN --skip-duplicate ./Packed/*nupkg
      
    - name: Creating release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
      
    - name: Get exact package name and path
      run: |
        echo "ARTIFACT_FNAME=$(ls ./Packed/*nupkg | grep -Po '(?<=/)[^/]+?$')" >> $GITHUB_ENV
        echo "ARTIFACT_PATH=$(ls ./Packed/*nupkg)" >> $GITHUB_ENV
        
    - name: Add artifact
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.ARTIFACT_PATH }}
        asset_name: ${{ env.ARTIFACT_FNAME }}
        asset_content_type: application/zip    


